# 122630 - KODEX 레버리지
# 233740 - KODEX 코스닥150 레버리지
# 069500 - KODEX 200
# 229200 - KODEX 코스닥 150
# 091170  - KODEX 은행,

### 웹소켓 열기
POST http://127.0.0.1:8083/trade/open HTTP/1.1
content-type: application/json

### 웹소켓 닫기
POST http://127.0.0.1:8083/trade/close HTTP/1.1
content-type: application/json

### 미국 실업률 통계
POST https://kr.investing.com/economic-calendar/more-history
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
x-requested-with: XMLHttpRequest
Content-Type: application/x-www-form-urlencoded

eventID=379991&event_attr_ID=300&event_timestamp=2023-07-01&is_speech=0

### 미국 실업률 통계
GET https://api.stlouisfed.org/fred/series/observations?series_id=UNRATE&api_key=<Key>&file_type=json HTTP/1.1
Content-Type: application/json

##################
# DART API
##################

### 고유번호 조회(압축파일 깨져서 받음, 쓰지마)
GET https://opendart.fss.or.kr/api/corpCode.xml?crtfc_key={{dart_key}}	HTTP/1.1
Content-Type: application/octet-stream
