package com.setvect.bokslstock2.koreainvestment.trade.model.response

import com.fasterxml.jackson.annotation.JsonProperty

data class CurrentPriceResponse(

    @JsonProperty("iscd_stat_cls_code") var iscdStatClsCode: String,
    @JsonProperty("marg_rate") var margRate: String,
    @JsonProperty("rprs_mrkt_kor_name") var rprsMrktKorName: String,
    @JsonProperty("bstp_kor_isnm") var bstpKorIsnm: String,
    @JsonProperty("temp_stop_yn") var tempStopYn: String,
    @JsonProperty("oprc_rang_cont_yn") var oprcRangContYn: String,
    @JsonProperty("clpr_rang_cont_yn") var clprRangContYn: String,
    @JsonProperty("crdt_able_yn") var crdtAbleYn: String,
    @JsonProperty("grmn_rate_cls_code") var grmnRateClsCode: String,
    @JsonProperty("elw_pblc_yn") var elwPblcYn: String,
    @JsonProperty("stck_prpr") var stckPrpr: String,
    @JsonProperty("prdy_vrss") var prdyVrss: String,
    @JsonProperty("prdy_vrss_sign") var prdyVrssSign: String,
    @JsonProperty("prdy_ctrt") var prdyCtrt: String,
    @JsonProperty("acml_tr_pbmn") var acmlTrPbmn: String,
    @JsonProperty("acml_vol") var acmlVol: String,
    @JsonProperty("prdy_vrss_vol_rate") var prdyVrssVolRate: String,
    @JsonProperty("stck_oprc") var stckOprc: String,
    @JsonProperty("stck_hgpr") var stckHgpr: String,
    @JsonProperty("stck_lwpr") var stckLwpr: String,
    @JsonProperty("stck_mxpr") var stckMxpr: String,
    @JsonProperty("stck_llam") var stckLlam: String,
    @JsonProperty("stck_sdpr") var stckSdpr: String,
    @JsonProperty("wghn_avrg_stck_prc") var wghnAvrgStckPrc: String,
    @JsonProperty("hts_frgn_ehrt") var htsFrgnEhrt: String,
    @JsonProperty("frgn_ntby_qty") var frgnNtbyQty: String,
    @JsonProperty("pgtr_ntby_qty") var pgtrNtbyQty: String,
    @JsonProperty("pvt_scnd_dmrs_prc") var pvtScndDmrsPrc: String,
    @JsonProperty("pvt_frst_dmrs_prc") var pvtFrstDmrsPrc: String,
    @JsonProperty("pvt_pont_val") var pvtPontVal: String,
    @JsonProperty("pvt_frst_dmsp_prc") var pvtFrstDmspPrc: String,
    @JsonProperty("pvt_scnd_dmsp_prc") var pvtScndDmspPrc: String,
    @JsonProperty("dmrs_val") var dmrsVal: String,
    @JsonProperty("dmsp_val") var dmspVal: String,
    @JsonProperty("cpfn") var cpfn: String,
    @JsonProperty("rstc_wdth_prc") var rstcWdthPrc: String,
    @JsonProperty("stck_fcam") var stckFcam: String,
    @JsonProperty("stck_sspr") var stckSspr: String,
    @JsonProperty("aspr_unit") var asprUnit: String,
    @JsonProperty("hts_deal_qty_unit_val") var htsDealQtyUnitVal: String,
    @JsonProperty("lstn_stcn") var lstnStcn: String,
    @JsonProperty("hts_avls") var htsAvls: String,
    @JsonProperty("per") var per: String,
    @JsonProperty("pbr") var pbr: String,
    @JsonProperty("stac_month") var stacMonth: String,
    @JsonProperty("vol_tnrt") var volTnrt: String,
    @JsonProperty("eps") var eps: String,
    @JsonProperty("bps") var bps: String,
    @JsonProperty("d250_hgpr") var d250Hgpr: String,
    @JsonProperty("d250_hgpr_date") var d250HgprDate: String,
    @JsonProperty("d250_hgpr_vrss_prpr_rate") var d250HgprVrssPrprRate: String,
    @JsonProperty("d250_lwpr") var d250Lwpr: String,
    @JsonProperty("d250_lwpr_date") var d250LwprDate: String,
    @JsonProperty("d250_lwpr_vrss_prpr_rate") var d250LwprVrssPrprRate: String,
    @JsonProperty("stck_dryy_hgpr") var stckDryyHgpr: String,
    @JsonProperty("dryy_hgpr_vrss_prpr_rate") var dryyHgprVrssPrprRate: String,
    @JsonProperty("dryy_hgpr_date") var dryyHgprDate: String,
    @JsonProperty("stck_dryy_lwpr") var stckDryyLwpr: String,
    @JsonProperty("dryy_lwpr_vrss_prpr_rate") var dryyLwprVrssPrprRate: String,
    @JsonProperty("dryy_lwpr_date") var dryyLwprDate: String,
    @JsonProperty("w52_hgpr") var w52Hgpr: String,
    @JsonProperty("w52_hgpr_vrss_prpr_ctrt") var w52HgprVrssPrprCtrt: String,
    @JsonProperty("w52_hgpr_date") var w52HgprDate: String,
    @JsonProperty("w52_lwpr") var w52Lwpr: String,
    @JsonProperty("w52_lwpr_vrss_prpr_ctrt") var w52LwprVrssPrprCtrt: String,
    @JsonProperty("w52_lwpr_date") var w52LwprDate: String,
    @JsonProperty("whol_loan_rmnd_rate") var wholLoanRmndRate: String,
    @JsonProperty("ssts_yn") var sstsYn: String,
    @JsonProperty("stck_shrn_iscd") var stckShrnIscd: String,
    @JsonProperty("fcam_cnnm") var fcamCnnm: String,
    @JsonProperty("cpfn_cnnm") var cpfnCnnm: String,
    @JsonProperty("frgn_hldn_qty") var frgnHldnQty: String,
    @JsonProperty("vi_cls_code") var viClsCode: String,
    @JsonProperty("ovtm_vi_cls_code") var ovtmViClsCode: String,
    @JsonProperty("last_ssts_cntg_qty") var lastSstsCntgQty: String,
    @JsonProperty("invt_caful_yn") var invtCafulYn: String,
    @JsonProperty("mrkt_warn_cls_code") var mrktWarnClsCode: String,
    @JsonProperty("short_over_yn") var shortOverYn: String,
    @JsonProperty("sltr_yn") var sltrYn: String

)