package com.setvect.bokslstock2.koreainvestment.trade.model.response

import com.fasterxml.jackson.annotation.JsonProperty

data class CurrentPriceResponse(

    @JsonProperty("iscd_stat_cls_code") val iscdStatClsCode: String,
    @JsonProperty("marg_rate") val margRate: String,
    @JsonProperty("rprs_mrkt_kor_name") val rprsMrktKorName: String,
    @JsonProperty("bstp_kor_isnm") val bstpKorIsnm: String,
    @JsonProperty("temp_stop_yn") val tempStopYn: String,
    @JsonProperty("oprc_rang_cont_yn") val oprcRangContYn: String,
    @JsonProperty("clpr_rang_cont_yn") val clprRangContYn: String,
    @JsonProperty("crdt_able_yn") val crdtAbleYn: String,
    @JsonProperty("grmn_rate_cls_code") val grmnRateClsCode: String,
    @JsonProperty("elw_pblc_yn") val elwPblcYn: String,
    @JsonProperty("stck_prpr") val stckPrpr: String,
    @JsonProperty("prdy_vrss") val prdyVrss: String,
    @JsonProperty("prdy_vrss_sign") val prdyVrssSign: String,
    @JsonProperty("prdy_ctrt") val prdyCtrt: String,
    @JsonProperty("acml_tr_pbmn") val acmlTrPbmn: String,
    @JsonProperty("acml_vol") val acmlVol: String,
    @JsonProperty("prdy_vrss_vol_rate") val prdyVrssVolRate: String,
    @JsonProperty("stck_oprc") val stckOprc: String,
    @JsonProperty("stck_hgpr") val stckHgpr: String,
    @JsonProperty("stck_lwpr") val stckLwpr: String,
    @JsonProperty("stck_mxpr") val stckMxpr: String,
    @JsonProperty("stck_llam") val stckLlam: String,
    @JsonProperty("stck_sdpr") val stckSdpr: String,
    @JsonProperty("wghn_avrg_stck_prc") val wghnAvrgStckPrc: String,
    @JsonProperty("hts_frgn_ehrt") val htsFrgnEhrt: String,
    @JsonProperty("frgn_ntby_qty") val frgnNtbyQty: String,
    @JsonProperty("pgtr_ntby_qty") val pgtrNtbyQty: String,
    @JsonProperty("pvt_scnd_dmrs_prc") val pvtScndDmrsPrc: String,
    @JsonProperty("pvt_frst_dmrs_prc") val pvtFrstDmrsPrc: String,
    @JsonProperty("pvt_pont_val") val pvtPontVal: String,
    @JsonProperty("pvt_frst_dmsp_prc") val pvtFrstDmspPrc: String,
    @JsonProperty("pvt_scnd_dmsp_prc") val pvtScndDmspPrc: String,
    @JsonProperty("dmrs_val") val dmrsVal: String,
    @JsonProperty("dmsp_val") val dmspVal: String,
    @JsonProperty("cpfn") val cpfn: String,
    @JsonProperty("rstc_wdth_prc") val rstcWdthPrc: String,
    @JsonProperty("stck_fcam") val stckFcam: String,
    @JsonProperty("stck_sspr") val stckSspr: String,
    @JsonProperty("aspr_unit") val asprUnit: String,
    @JsonProperty("hts_deal_qty_unit_val") val htsDealQtyUnitVal: String,
    @JsonProperty("lstn_stcn") val lstnStcn: String,
    @JsonProperty("hts_avls") val htsAvls: String,
    @JsonProperty("per") val per: String,
    @JsonProperty("pbr") val pbr: String,
    @JsonProperty("stac_month") val stacMonth: String,
    @JsonProperty("vol_tnrt") val volTnrt: String,
    @JsonProperty("eps") val eps: String,
    @JsonProperty("bps") val bps: String,
    @JsonProperty("d250_hgpr") val d250Hgpr: String,
    @JsonProperty("d250_hgpr_date") val d250HgprDate: String,
    @JsonProperty("d250_hgpr_vrss_prpr_rate") val d250HgprVrssPrprRate: String,
    @JsonProperty("d250_lwpr") val d250Lwpr: String,
    @JsonProperty("d250_lwpr_date") val d250LwprDate: String,
    @JsonProperty("d250_lwpr_vrss_prpr_rate") val d250LwprVrssPrprRate: String,
    @JsonProperty("stck_dryy_hgpr") val stckDryyHgpr: String,
    @JsonProperty("dryy_hgpr_vrss_prpr_rate") val dryyHgprVrssPrprRate: String,
    @JsonProperty("dryy_hgpr_date") val dryyHgprDate: String,
    @JsonProperty("stck_dryy_lwpr") val stckDryyLwpr: String,
    @JsonProperty("dryy_lwpr_vrss_prpr_rate") val dryyLwprVrssPrprRate: String,
    @JsonProperty("dryy_lwpr_date") val dryyLwprDate: String,
    @JsonProperty("w52_hgpr") val w52Hgpr: String,
    @JsonProperty("w52_hgpr_vrss_prpr_ctrt") val w52HgprVrssPrprCtrt: String,
    @JsonProperty("w52_hgpr_date") val w52HgprDate: String,
    @JsonProperty("w52_lwpr") val w52Lwpr: String,
    @JsonProperty("w52_lwpr_vrss_prpr_ctrt") val w52LwprVrssPrprCtrt: String,
    @JsonProperty("w52_lwpr_date") val w52LwprDate: String,
    @JsonProperty("whol_loan_rmnd_rate") val wholLoanRmndRate: String,
    @JsonProperty("ssts_yn") val sstsYn: String,
    @JsonProperty("stck_shrn_iscd") val stckShrnIscd: String,
    @JsonProperty("fcam_cnnm") val fcamCnnm: String,
    @JsonProperty("cpfn_cnnm") val cpfnCnnm: String,
    @JsonProperty("frgn_hldn_qty") val frgnHldnQty: String,
    @JsonProperty("vi_cls_code") val viClsCode: String,
    @JsonProperty("ovtm_vi_cls_code") val ovtmViClsCode: String,
    @JsonProperty("last_ssts_cntg_qty") val lastSstsCntgQty: String,
    @JsonProperty("invt_caful_yn") val invtCafulYn: String,
    @JsonProperty("mrkt_warn_cls_code") val mrktWarnClsCode: String,
    @JsonProperty("short_over_yn") val shortOverYn: String,
    @JsonProperty("sltr_yn") val sltrYn: String

)