package com.setvect.bokslstock2.koreainvestment.trade.model.response

import com.fasterxml.jackson.annotation.JsonProperty

data class QuoteResponse(

    @JsonProperty("output1") val output1: QuoteLevel?,
    @JsonProperty("output2") val output2: QuoteInfo?,
    @JsonProperty("rt_cd") val rtCd: String,
    @JsonProperty("msg_cd") val msgCd: String,
    @JsonProperty("msg1") val msg1: String
) {

    data class QuoteLevel(
        @JsonProperty("aspr_acpt_hour") val asprAcptHour: String,
        @JsonProperty("askp1") val askp1: String,
        @JsonProperty("askp2") val askp2: String,
        @JsonProperty("askp3") val askp3: String,
        @JsonProperty("askp4") val askp4: String,
        @JsonProperty("askp5") val askp5: String,
        @JsonProperty("askp6") val askp6: String,
        @JsonProperty("askp7") val askp7: String,
        @JsonProperty("askp8") val askp8: String,
        @JsonProperty("askp9") val askp9: String,
        @JsonProperty("askp10") val askp10: String,
        @JsonProperty("bidp1") val bidp1: String,
        @JsonProperty("bidp2") val bidp2: String,
        @JsonProperty("bidp3") val bidp3: String,
        @JsonProperty("bidp4") val bidp4: String,
        @JsonProperty("bidp5") val bidp5: String,
        @JsonProperty("bidp6") val bidp6: String,
        @JsonProperty("bidp7") val bidp7: String,
        @JsonProperty("bidp8") val bidp8: String,
        @JsonProperty("bidp9") val bidp9: String,
        @JsonProperty("bidp10") val bidp10: String,
        @JsonProperty("askp_rsqn1") val askpRsqn1: String,
        @JsonProperty("askp_rsqn2") val askpRsqn2: String,
        @JsonProperty("askp_rsqn3") val askpRsqn3: String,
        @JsonProperty("askp_rsqn4") val askpRsqn4: String,
        @JsonProperty("askp_rsqn5") val askpRsqn5: String,
        @JsonProperty("askp_rsqn6") val askpRsqn6: String,
        @JsonProperty("askp_rsqn7") val askpRsqn7: String,
        @JsonProperty("askp_rsqn8") val askpRsqn8: String,
        @JsonProperty("askp_rsqn9") val askpRsqn9: String,
        @JsonProperty("askp_rsqn10") val askpRsqn10: String,
        @JsonProperty("bidp_rsqn1") val bidpRsqn1: String,
        @JsonProperty("bidp_rsqn2") val bidpRsqn2: String,
        @JsonProperty("bidp_rsqn3") val bidpRsqn3: String,
        @JsonProperty("bidp_rsqn4") val bidpRsqn4: String,
        @JsonProperty("bidp_rsqn5") val bidpRsqn5: String,
        @JsonProperty("bidp_rsqn6") val bidpRsqn6: String,
        @JsonProperty("bidp_rsqn7") val bidpRsqn7: String,
        @JsonProperty("bidp_rsqn8") val bidpRsqn8: String,
        @JsonProperty("bidp_rsqn9") val bidpRsqn9: String,
        @JsonProperty("bidp_rsqn10") val bidpRsqn10: String,
        @JsonProperty("askp_rsqn_icdc1") val askpRsqnIcdc1: String,
        @JsonProperty("askp_rsqn_icdc2") val askpRsqnIcdc2: String,
        @JsonProperty("askp_rsqn_icdc3") val askpRsqnIcdc3: String,
        @JsonProperty("askp_rsqn_icdc4") val askpRsqnIcdc4: String,
        @JsonProperty("askp_rsqn_icdc5") val askpRsqnIcdc5: String,
        @JsonProperty("askp_rsqn_icdc6") val askpRsqnIcdc6: String,
        @JsonProperty("askp_rsqn_icdc7") val askpRsqnIcdc7: String,
        @JsonProperty("askp_rsqn_icdc8") val askpRsqnIcdc8: String,
        @JsonProperty("askp_rsqn_icdc9") val askpRsqnIcdc9: String,
        @JsonProperty("askp_rsqn_icdc10") val askpRsqnIcdc10: String,
        @JsonProperty("bidp_rsqn_icdc1") val bidpRsqnIcdc1: String,
        @JsonProperty("bidp_rsqn_icdc2") val bidpRsqnIcdc2: String,
        @JsonProperty("bidp_rsqn_icdc3") val bidpRsqnIcdc3: String,
        @JsonProperty("bidp_rsqn_icdc4") val bidpRsqnIcdc4: String,
        @JsonProperty("bidp_rsqn_icdc5") val bidpRsqnIcdc5: String,
        @JsonProperty("bidp_rsqn_icdc6") val bidpRsqnIcdc6: String,
        @JsonProperty("bidp_rsqn_icdc7") val bidpRsqnIcdc7: String,
        @JsonProperty("bidp_rsqn_icdc8") val bidpRsqnIcdc8: String,
        @JsonProperty("bidp_rsqn_icdc9") val bidpRsqnIcdc9: String,
        @JsonProperty("bidp_rsqn_icdc10") val bidpRsqnIcdc10: String,
        @JsonProperty("total_askp_rsqn") val totalAskpRsqn: String,
        @JsonProperty("total_bidp_rsqn") val totalBidpRsqn: String,
        @JsonProperty("total_askp_rsqn_icdc") val totalAskpRsqnIcdc: String,
        @JsonProperty("total_bidp_rsqn_icdc") val totalBidpRsqnIcdc: String,
        @JsonProperty("ovtm_total_askp_icdc") val ovtmTotalAskpIcdc: String,
        @JsonProperty("ovtm_total_bidp_icdc") val ovtmTotalBidpIcdc: String,
        @JsonProperty("ovtm_total_askp_rsqn") val ovtmTotalAskpRsqn: String,
        @JsonProperty("ovtm_total_bidp_rsqn") val ovtmTotalBidpRsqn: String,
        @JsonProperty("ntby_aspr_rsqn") val ntbyAsprRsqn: String,
        @JsonProperty("new_mkop_cls_code") val newMkopClsCode: String
    )

    data class QuoteInfo(
        @JsonProperty("antc_mkop_cls_code") val antcMkopClsCode: String,
        @JsonProperty("stck_prpr") val stckPrpr: String,
        @JsonProperty("stck_oprc") val stckOprc: String,
        @JsonProperty("stck_hgpr") val stckHgpr: String,
        @JsonProperty("stck_lwpr") val stckLwpr: String,
        @JsonProperty("stck_sdpr") val stckSdpr: String,
        @JsonProperty("antc_cnpr") val antcCnpr: String,
        @JsonProperty("antc_cntg_vrss_sign") val antcCntgVrssSign: String,
        @JsonProperty("antc_cntg_vrss") val antcCntgVrss: String,
        @JsonProperty("antc_cntg_prdy_ctrt") val antcCntgPrdyCtrt: String,
        @JsonProperty("antc_vol") val antcVol: String,
        @JsonProperty("stck_shrn_iscd") val stckShrnIscd: String,
        @JsonProperty("vi_cls_code") val viClsCode: String
    )
}